GET http://localhost:9000/usuario?page=1&pageSize=10&sortBy=email&order=asc&filters={"email":"admin"}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZGFtczMyMjEyMkBlbWFpbC5jb20iLCJpYXQiOjE3MjI5NDQ3NTIsImV4cCI6MTcyMjk0ODM1Mn0.RJd0LkkqwK-E94gQkaXO2XzvJS3wRxW76c-HgkDMusM

###
GET http://localhost:9000/usuariofuncao?page=1&pageSize=10&order=asc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZGFtczMyMjEyMkBlbWFpbC5jb20iLCJpYXQiOjE3MjI5NTE0NDgsImV4cCI6MTcyMjk1NTA0OH0.5wLCkDOtlqB3IeT6pV8z88qePhE5IYfDl4xkFkOvxVA


GET http://localhost:9000/usuario?page=1&pageSize=10&search=test&sortBy=email&order=asc&filters={"ativo":"1"}

###
POST http://localhost:9000/usuario
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZGFtczMyMjEyMkBlbWFpbC5jb20iLCJpYXQiOjE3MjI1MTM2ODUsImV4cCI6MTcyMjUxNzI4NX0.ppsrnaaIsIVGnZdguH9hby3w4akRqYlVtxl00Q4C_-E

{
  "email": "adams32@email.com",
  "login": "adams2",
  "senha": "senha",
  "nomeCompleto": "testeteste"

}

###
POST http://localhost:9000/usuario
Content-Type: application/json
Accept: application/json

{
  "email": "adams2@email.com",
  "login": "adams2",
  "senha": "senha",
  "nomeCompleto": "testeteste"

}


###
PUT  http://localhost:9000/usuario/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZGFtczMyMjEyMkBlbWFpbC5jb20iLCJpYXQiOjE3MjI1MTM2ODUsImV4cCI6MTcyMjUxNzI4NX0.ppsrnaaIsIVGnZdguH9hby3w4akRqYlVtxl00Q4C_-E

{
  "email": "exempsdfasdaaaaafoedit@email.com",
  "ativo": false,
  "senha": "12345"

}


###
DELETE  http://localhost:9000/usuario/8


###
POST http://localhost:9000/login
Content-Type: application/json
Accept: application/json

{
  "login": "adams22123",  
  "senha": "senha"
}


###
POST http://localhost:9000/addlogin
Content-Type: application/json
Accept: application/json

{
  "email": "adams322122@email.com",
  "login": "adams22123",
  "senha": "senha"
}